### ISSUE TITLE
Rule

### ISSUE THREAD

**Issue by yoomambo** [yoomambo/festival#1]
- commit 

`git commit -m "user : commit하는 내용들 "`

user 에는 mambo, gaejuk_2

commit 하는 내용들 에는 기능 추가, 변경 내용들을 상세히 적는다.

- branch 명 

gaejuk_2 는 G_(branch 목적)

mambo 는 M_(branch 목적) 으로 명을 한다.

알파벳_ 뒤에는 branch의 목적을 알아보기 편하게만 적어주고

거기에서도 버젼을 나눌 경우에는 _ 언더바를 이용해서 세분화한다.

- branch 관리

서로 의견 수렴 후, branch 를 merge한다.

**Comment by Gaejuk2** [comment]
commit에도 라벨이 있는게 좋을 것 같습니다. 지금까지 제가 커밋하던 방식은
```
[Label]:title

target files

detail
```
이었으며, Label은 다음과 같이 분류하였습니다.
* Doc : 문서관련
* Add : 새로운 기능
* Ref : 리팩토링
* Bug : 버그 수정
* Del : 삭제

**Comment by Gaejuk2** [comment]
따라서 라벨도 추가하여 
* [Doc]_G:Readme 수정
* [Add]_M:Crawling
의 식으로 정하면 어떨까요?

**Comment by yoomambo** [comment]
commit 에 대한 경우는 제일 앞에는 user로 구분해주는 편이 좋을 것 같습니다.

- [ ] M[Label]:Readme 

- [ ] G[Add]:Crawling 

이런 순으로 하면 어떨까요?

**Comment by Gaejuk2** [comment]
commit한 사람이 앞에와도 상관없습니다. 그렇게 진행하죠.
