### ISSUE TITLE
due date: 11/11

### ISSUE THREAD

**Issue by Gaejuk2** [yoomambo/festival#4]

**Comment by Gaejuk2** [comment]
- [ ] 웹페이지 완성
- [ ] 서버 준비
- [ ] SQL문 준비

**Comment by yoomambo** [comment]
- [ ] user에게 받은 History db 불러와서 그 route에 username.db 파일 만들기
- [ ] username.db들을 모아서 final_database.db 에 중복있는 경우 count하는 쿼리문까지 작성
- [ ] 토크나이징 담당
