### ISSUE TITLE
user들의 history.db merge 하는 과정

### ISSUE THREAD

**Issue by yoomambo** [yoomambo/festival#5]
user_history_merge.py 에서
개별 history가 업데이트 될 때마다 all_users_history 를 업데이트해야하는데, 
속성들은 (url, title, visit_count, user_count)로 , user_count의 default값은 1입니다.
user들마다 겹치는 url이 있을 경우, user들의 history를 불러올 떄마다 1을 추가해줍니다.

이 과정에서 update를 자주하면 전에 업데이트하는것과 구별짓기 힘듭니다.

그래서 두 가지 문제점이 생겼습니다.

- 만약 구별하려면, 속성에 무엇을 더 추가할지.
- 만약 구별하지 않고, all_users_history.db 파일을 url 추출해주고 다 지우고, 나중에 client가 검색어 창을 다시 누를 때 다시 업데이트 해야할지.
    -이 알고리즘을 쓴다면, 한 db만 부르는데 1초정도 걸립니다. 

혹시 알고리즘 개선해야하는지, 아니면 이 정도 시간이면 괜찮을지.
개선방안이 필요합니다.

**Comment by yoomambo** [comment]
- 추가로 말하자면, 처음 History_all_users.db 구축하는데 1초지만,
- 모든 url이 다 겹쳤다고 가정하자면, 50초 정도 걸립니다.

**Comment by Gaejuk2** [comment]
"전에 업데이트 하는 것과 구별짓기 힘들다"는 뜻이 어떤 뜻이며, 왜 구별지어야하는 건가요?
