### ISSUE TITLE
due date: 11/17

### ISSUE THREAD

**Issue by yoomambo** [yoomambo/festival#7]
- [x] PageRank 논문 찾아보기
- [x] Token tool 다시 찾아보기
- [x] python -> bisect 로 돌려보기
- [x] keyword 추출
- [x] 검색시간 확인하기
- [ ] db구축하는 것 pyspark.pandas 공부해서 해보기

**Comment by Gaejuk2** [comment]
- [ ] 사용자의 History를 다운로드 승인을 요청하는 안내문
- [ ] History 다운로드 기능
- [ ] Keyword 검색 기능
