### ISSUE TITLE
Q&A : 알고리즘 과정

### ISSUE THREAD

**Issue by yoomambo** [yoomambo/festival#8]
저번에 전화로 말씀드린 keyword 추출 관해서 말씀드리려 합니다.

일단 database에는 영어, 한글을 RegexTokenizer로 나눈 후,
한글은 조사가 붙기 때문에 Okt라는 모듈을 사용해서 명사만 추출한 후, DB table에 저장하였습니다.
table에는 명사만 들어있습니다.

user_keyword = " ['computer의 Youtube채널 channel확인하기 "    라는 input list 값이 있습니다.

---------------------------------------------------------------------------------------------------------------
1. RegexTokenizer라는 모듈을 사용하면

output: 

[ "['", 'computer', '의', 'Youtube', '채널', 'channel', '확인하기' ] 이 나옵니다.

2. RegexTokenizer를 사용하고, 

한글만, Okt로 명사만 추출한 후, 

output :

['computer', '의', 'youtube', '채널', 'channel', '확인']

---------------------------------------------------------------------------------------------------------------

여기서 1번 과정은 0.1초, 거의 바로 나오고, 2번 과정은 Okt를 거쳐서 그런지 2초 정도 걸립니다.

그래서 지금 문제가 되는 부분은 1번 과정은 매우 빠르지만, 진행하면 ' 확인하기 ' 라는 데이터는
DB table에 존재하지 않습니다. DB table에는 명사만 저장되어있기 때문입니다.

2번 과정은 input 과정에서 1번과정보다 매우 느리지만, data가 전처리가 상대적으로 잘 되어있어,  DB table에서 찾는 것은 매우 빠릅니다.

---------------------------------------------------------------------------------------------------------------

- 1번 과정으로 하게 되면, user들이 입력을 할 때
['computer의 Youtube채널 channel확인하기 -> computer의 Youtube 채널 channel 확인
이렇게 입력받게 유의사항에 적어두어야 할 것 같습니다.

- 2번 과정으로 하게 되면, user들이 입력을 하고 나서
시간을 끌만한 소재, 예를 들어 모래시계나 이런 아이콘을 보여주거나 할만한게 필요하지 않을까 합니다.

**Comment by Gaejuk2** [comment]
명사로 추출하는 과정이 어떻게 되나요?
input이 "computer의 Youtube채널 channel확인" 일 경우에도 2초가 걸리는 건가요?

"확인하기"와 "확인"의 경우가 시간이 다르게 걸린다면, 2번 과정을 택하지만, 빠른 검색을 위한 유의사항을 추가하는 방향으로 가도 괜찮을 것 같습니다.
